### ISSUE TITLE
[Backend] Ability to remove chapters, non-profits 

### ISSUE THREAD

**Issue by shashanklal01** [GTBitsOfGood/national-npp#78]
## What/Why?
Admin-only feature to remove chapters, non-profits from the system.

#### Chapter
1. API call must completely delete any information pertaining to the chapter.
2. If not already existing, create a table which stores name of chapter that is removed, and timestamp of removal - and populate table on each removal.
3. Email chapter notifying they have been removed due to X reason (String input).

#### Non-Profit
1. API call must completely delete any information pertaining to the non-profit.
2. If not already existing, create a table which stores name of non-profit that is removed, and timestamp of removal - and populate table on each removal.
3. Email non-profit notifying they have been removed due to X reason (String input).

**Comment by Navbryce** [comment]
Can any kind of admin remove a chapter or just national admins? Same question with nonprofits

**Comment by shashanklal01** [comment]
@Navbryce Only national admins can remove chapters and non-profits for now.
